# seconds between each automatic spread check
infection-interval-seconds: 300

# radius around each infected player to attempt spread
proximity-radius: 5.0

# chance [0.0-1.0] to infect when within proximity
proximity-chance: 0.25

# chance [0.0-1.0] to infect on player-vs-player hit
hit-chance: 0.35

# Chance [0.0–1.0] that eating a golden apple while Weakness will cure SAGE-19
cure-success-chance: 0.95

# new toggle for whether golden-apple curing is active
curing-enabled: false

# Chance [0.0–1.0] that a carved‐pumpkin wearer still gets infected
mask-infection-chance: 0.05

# The chance of a culture dropping from a cured person (5% default)
culture-drop-chance: 0.05

# the chance of a player being pure infected from a splash potion (default 25%)
pure-infect-splash-chance: 0.25